external_templates:
  file: config/overlays/config/templates.yml

### TMDB TRENDING / IMDB AWARDS ###

overlays:
  imdb_250:
    template: {name: IMDB, group: "awards", weight: 799, top: 250}
  imdb_1000:
    template: {name: IMDB, group: "awards", weight: 798, top: 1000}

### TMDB TRENDING / IMDB AWARDS ###